ktor:
  application:
    modules:
      - com.lessonarchiver.ApplicationKt.module
  deployment:
    port: 8080

notary:
  client: lessonarchiver
  url: $NOTARY_URL:https://auth.lessonarchiver.com
  callback: $NOTARY_CALLBACK:https://app.lessonarchiver.com/token
  key: $NOTARY_KEY

db:
  url: $POSTGRES_URL
  username: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD

b2:
  applicationKeyId: $B2_APPLICATION_KEY_ID
  applicationKey: $B2_APPLICATION_KEY
  bucketId: $B2_BUCKET_ID:c1e49a04379946be9f99021f

es:
  scheme: $ELASTIC_SCHEME:https
  host: $ELASTIC_HOST:localhost
  port: $ELASTIC_PORT:443
  username: $ELASTIC_USERNAME:elastic
  password: $ELASTIC_PASSWORD

mode: dev